# Generated by Django 4.2.11 on 2024-07-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_child1_item_child2_item_child3_item_child4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='college_school_address',
            new_name='college_school_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='elementary_school_address',
            new_name='elementary_school_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='secondary_school_address',
            new_name='secondary_school_name',
        ),
    ]
