# Generated by Django 4.2.11 on 2024-07-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_college_school_address_item_college_school_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='father_surname',
            new_name='father_last_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='mother_surname',
            new_name='mother_last_name',
        ),
    ]
